export const USER_ACTION_TYPES = {
    SET_CURRENT_USER : 'user/SET_CURRENT_USER',
    CHECK_USER_SESSION : 'user/CHECK_USER_SESSION',
    GOOGLE_SIGNIN_START : 'user/GOOGLE_SIGNIN_START',
    EMAIL_SIGNIN_START : 'user/EMAIL_SIGNIN_START',
    SIGNIN_SUCCESS : 'user/SIGNIN_SUCCESS',
    SIGNIN_FAILURE : 'user/SIGNIN_FAILURE',
    SIGNUP_START :   'user/SIGNUP_START',
    SIGNUP_SUCCESS : 'user/SIGNUP_SUCCESS',
    SIGNUP_FAILURE : 'user/SIGNUP_FAILURE',
    SIGNOUT_START : 'user/SIGNOUT_START',
    SIGNOUT_SUCCESS : 'user/SIGNOUT_SUCCESS',
    SIGNOUT_FAILURE : 'user/SIGNOUT_FAILURE'
};